### ISSUE TITLE
Bydate

### ISSUE THREAD

**Issue by jenstornell** [jenstornell/kirby-plugins#9]
https://github.com/studiodumbar/kirby-extensions/tree/master/plugins/bydate

> A plugin for Kirby CMS that helps working with dated pages, such as blog posts. Provides a pagesByDate function for your templates. Tested on Kirby 1 and 2.

**Comment by fvsch** [comment]
Since this is a copy or fork of https://github.com/fvsch/kirby-bydate (which is referenced here in #151), it might be better to close this issue to avoid duplication. @jolantis, would it be okay to close, or is it a fork with different features?

For the record I know consider this plugin (my version at least) to be deprecated, because core additions to Kirby 2.0 and 2.1 match its feature set in a more elegant way.

**Comment by jenstornell** [comment]
It's not updated in 2 years. I'm closing it. @jolantis. Write a comment if you want me to repoen it.

**Comment by jolantis** [comment]
Off course it's fine. I removed the ‘copy’ of the Bydate plugin form my repository. Thanks.
